/* Menus HTML acessíveis sobre o canvas. Sem dependências nem fontes remotas. */
(function(){
  "use strict";
  var root=null,view="free",lastRace=null,choice={track:0,driver:1,level:1,laps:3,mode:"free",mirror:false,cup:0};
  var nickname='Piloto',roomInput='';
  var tabs=[["free","Corrida livre"],["online","Jogar com amigos"],["cups","Campeonato"],["garage","Oficina"],["records","Recordes"],["options","Opções"],["guide","Como jogar"]];
  function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function button(text,action,attrs){return '<button type="button" data-action="'+action+'" '+(attrs||'')+'>'+text+'</button>';}
  function selected(a,b){return a===b?' selected':'';}
  function header(){return '<header class="menu-head"><div class="brand"><span class="brand-bolt" aria-hidden="true">ϟ</span><div><strong>KART TROVÃO <em>16</em></strong><span>GRAND TOUR</span></div></div><div class="wallet"><b>'+KT.Career.data.bolts+'</b><span>Parafusos</span></div></header><nav class="menu-tabs" aria-label="Modos e opções">'+tabs.map(function(t){return button(t[1],'tab:'+t[0],view===t[0]?'aria-current="page"':'');}).join('')+'</nav>';}
  function levelSelect(){return '<label>Dificuldade<select id="level">'+KT.LEVELS.map(function(l,i){return '<option value="'+i+'"'+selected(choice.level,i)+(i===3&&!KT.Career.legend()?' disabled':'')+'>'+l.name+(i===3&&!KT.Career.legend()?' · bloqueado':'')+'</option>';}).join('')+'</select></label>';}
  function driverSelect(){return '<div class="driver-heading"><h3>Piloto</h3><span>'+KT.DRIVERS[choice.driver].perfil+'</span></div><div class="driver-roster">'+KT.DRIVERS.map(function(d,i){var unlocked=KT.Career.unlockedDriver(i);return button('<canvas width="24" height="24" data-face="'+i+'" aria-hidden="true"></canvas><span>'+d.nome+'</span>'+(!unlocked?'<small>'+ (i===8?'5 vitórias':'Pódio na copa')+'</small>':''),'driver:'+i,'class="driver-button" aria-pressed="'+(choice.driver===i)+'" title="'+d.nome+'" '+(!unlocked?'disabled':''));}).join('')+'</div>';}
  function stats(){var d=KT.DRIVERS[choice.driver];return '<div class="driver-stats">'+[['Velocidade',d.vel],['Aceleração',d.acel],['Aderência',d.grip]].map(function(a){return '<span>'+a[0]+'<meter min="0.85" max="1.12" value="'+a[1]+'">'+Math.round(a[1]*100)+'</meter></span>';}).join('')+'</div>';}
  function online(){var net=KT.Net,connected=net.connected,busy=net.phase==='connecting',lobby=net.phase==='lobby';
    return '<div class="page-heading"><div><span class="kicker">ATÉ 4 AMIGOS + IA</span><h1>Uma sala. Oito karts.</h1></div><p>Crie uma sala e compartilhe o convite. Os lugares livres ficam com a IA. Peças padrão para todos.</p></div>'+
    (connected?'<div class="online-lobby"><section><label>Código da sala</label><output class="room-code">'+esc(net.code||'••••••••')+'</output><label>Link do convite<input id="invite-link" readonly value="'+esc(net.code?net.invite():'Gerando convite...')+'"></label><div class="button-row">'+button('Copiar convite','copy-invite',net.code?'':'disabled')+button(net.host?'Encerrar sala':'Sair da sala','leave-online')+'</div><p class="online-status" role="status">'+esc(net.message)+'</p><h2>Pilotos · '+net.players.length+'/4</h2><ol class="online-players">'+net.players.map(function(p,i){return '<li><span class="player-dot" style="background:'+KT.DRIVERS[p.driver].cor+'"></span><b>'+esc(p.name)+'</b><span>'+KT.DRIVERS[p.driver].nome+(i===0?' · anfitrião':'')+'</span></li>';}).join('')+'</ol><p>'+(8-net.players.length)+' karts serão pilotados pela IA.</p></section><section class="online-rules"><h2>'+esc(KT.TRACKS[net.settings.pista]?.name||'Conectando')+'</h2><p>'+esc(KT.LEVELS[net.settings.nivel]?.name||'')+' · '+(net.settings.voltas||3)+' voltas'+(net.settings.espelho?' · espelhado':'')+'</p><p>O anfitrião inicia a corrida quando todos estiverem aqui. Durante a corrida não há pausa; sair do anfitrião encerra a conexão de todos.</p>'+button(net.host?'INICIAR CORRIDA':'AGUARDANDO ANFITRIÃO','start-online','class="primary start-race" '+(!lobby||!net.host||net.players.length<2?'disabled':''))+'<small>Mantenha a aba do jogo em primeiro plano durante a partida.</small></section></div>':
    '<div class="online-identity"><label>Seu apelido<input id="online-name" maxlength="18" value="'+esc(nickname)+'" autocomplete="nickname"></label><label>Piloto<select id="online-driver">'+KT.DRIVERS.map(function(d,i){return '<option value="'+i+'"'+selected(choice.driver,i)+(!KT.Career.unlockedDriver(i)?' disabled':'')+'>'+d.nome+'</option>';}).join('')+'</select></label></div><div class="online-columns"><section><h2>Criar sala</h2><p>Escolha a corrida e convide até três amigos.</p><label>Circuito<select id="track">'+KT.TRACKS.map(function(t){return '<option value="'+t.id+'"'+selected(choice.track,t.id)+'>'+t.name+'</option>';}).join('')+'</select></label><div class="setup-fields">'+levelSelect()+'<label>Voltas<select id="laps">'+[1,2,3,4,5].map(function(i){return '<option'+selected(choice.laps,i)+'>'+i+'</option>';}).join('')+'</select></label></div>'+button('CRIAR SALA','create-online','class="primary start-race" '+(busy?'disabled':''))+'</section><section><h2>Entrar com convite</h2><p>Recebeu um código? Cole aqui. O link da sala também funciona.</p><label>Código ou link<input id="room-input" maxlength="400" placeholder="Ex.: K7MP4R2A" value="'+esc(roomInput)+'" autocomplete="off" spellcheck="false"></label>'+button('ENTRAR NA SALA','join-online','class="primary start-race" '+(busy?'disabled':''))+'<p class="online-status" role="status">'+esc(net.message)+'</p></section></div>')+
    '<p class="online-help">Requer internet e um link público para amigos em outros computadores. O modo solo continua offline. A conexão usa PeerServer Cloud e WebRTC; algumas redes restritas precisam de retransmissão TURN.</p>';
  }
  function free(){var t=KT.TRACKS[choice.track],theme=KT.THEMES[t.theme];return '<div class="menu-columns"><section class="circuit-panel"><div class="section-top"><span>'+KT.CUPS[t.cup].name+'</span><span>'+String(t.id+1).padStart(2,'0')+' / 30</span></div><h1>'+t.name+'</h1><div class="track-preview" style="--theme-accent:'+theme.accent+'"><canvas id="track-map" width="460" height="300" aria-label="Traçado de '+t.name+'"></canvas><span class="biome">'+theme.name+'</span></div><div class="track-controls">'+button('←','track:-1','aria-label="Pista anterior"')+'<label class="sr-only" for="track">Circuito</label><select id="track">'+KT.TRACKS.map(function(t){return '<option value="'+t.id+'"'+selected(choice.track,t.id)+'>'+String(t.id+1).padStart(2,'0')+' · '+t.name+'</option>';}).join('')+'</select>'+button('→','track:1','aria-label="Próxima pista"')+'</div><p class="track-note">'+t.description+'</p><div class="race-rules"><span>8 karts</span><span>6 itens</span><span>3 cargas de drift</span></div></section><section class="setup-panel">'+driverSelect()+stats()+'<div class="setup-fields"><label>Modo<select id="mode"><option value="free"'+selected(choice.mode,'free')+'>Corrida livre</option><option value="tt"'+selected(choice.mode,'tt')+'>Contrarrelógio</option></select></label>'+levelSelect()+'<label>Voltas<select id="laps"'+(choice.mode==='tt'?' disabled':'')+'>'+[1,2,3,4,5].map(function(i){return '<option'+selected(choice.laps,i)+'>'+i+'</option>';}).join('')+'</select></label><label>Sentido<select id="mirror"><option value="0"'+selected(choice.mirror,false)+'>Original</option><option value="1"'+selected(choice.mirror,true)+'>Espelhado</option></select></label></div><p class="setup-note">'+(choice.mode==='tt'?'Você e seu melhor fantasma. 3 voltas, sem itens e com peças padrão.':KT.LEVELS[choice.level].note)+'</p>'+button('IR PARA A LARGADA <span aria-hidden="true">→</span>','start','class="primary start-race"')+'</section></div>';}
  function cups(){var a=KT.Career.data.activeCup,c=KT.CUPS[choice.cup],open=KT.Career.unlockedCup(choice.cup);return '<div class="cup-page"><div class="page-heading"><div><span class="kicker">30 CIRCUITOS. UM CAMPEÃO.</span><h1>O caminho até o Trovão</h1></div><p>Dez etapas por copa. Some pontos, conquiste um pódio e libere o próximo desafio.</p></div>'+(a?'<div class="resume-cup"><div><b>'+KT.CUPS[a.cup].name+' em andamento</b><span>Etapa '+(a.stage+1)+'/10 · '+KT.DRIVERS[a.player].nome+' · '+KT.LEVELS[a.level].name+'</span></div>'+button('Continuar copa','resume-cup','class="primary"')+'</div>':'')+'<div class="cup-picker">'+KT.CUPS.map(function(c,i){var open=KT.Career.unlockedCup(i),medals=[0,1,2,3].map(function(l){var p=KT.Career.data.cups[i+":"+l];return p?KT.LEVELS[l].name+': '+p+'º':'';}).filter(Boolean).join(' · ');return button('<span class="cup-trophy" style="color:'+c.color+'" aria-hidden="true">♜</span><strong>'+c.name+'</strong><small>'+(open?'10 circuitos · '+c.prize+' Parafusos de bônus':'Pódio na '+KT.CUPS[i-1].name)+'</small><small>'+esc(medals||'Sem troféus ainda')+'</small>','cup:'+i,'aria-pressed="'+(choice.cup===i)+'"');}).join('')+'</div><div class="cup-detail"><section><h2>'+c.name+'</h2><p>Rival: <b>'+KT.DRIVERS[c.rival].nome+'</b>. Pódio libera o rival como piloto e dá o bônus da copa. Vencer as três no ÁS libera LENDA.</p><ol class="stage-list">'+KT.TRACKS.filter(function(t){return t.cup===choice.cup;}).map(function(t){return '<li><span>'+t.name+'</span><small>'+KT.THEMES[t.theme].name+'</small></li>';}).join('')+'</ol></section><section>'+driverSelect()+stats()+levelSelect()+'<p class="setup-note">Pontos: 15, 12, 10, 8, 6, 4, 2, 1. Empates compartilham a posição. Save automático após cada etapa.</p>'+button(open?'INICIAR COPA':'COPA BLOQUEADA','begin-cup','class="primary start-race" '+(!open?'disabled':''))+'</section></div></div>';}
  function garage(){var d=KT.Career.data;return '<div class="page-heading"><div><span class="kicker">OFICINA DO DR. PARAFUSO</span><h1>Seu kart. Seu jeito de correr.</h1></div><p>Peças permanentes para corridas livres e copas. O contrarrelógio usa configuração padrão.</p></div><div class="garage-layout"><section class="garage-kart"><canvas id="garage-preview" width="220" height="140" aria-label="Seu kart personalizado"></canvas><h2>'+KT.DRIVERS[choice.driver].nome+'</h2><label>Pintura</label><div class="paint-options">'+KT.Career.paints.map(function(c,i){return button('<i style="background:'+(c||KT.DRIVERS[choice.driver].cor)+'"></i>','paint:'+i,'aria-label="'+(['Original','Solar','Menta','Rosa','Lilás','Pérola'][i])+'" aria-pressed="'+(d.paint===i)+'"');}).join('')+'</div><p>Pinturas gratuitas. Experimente!</p></section><section class="parts-list">'+[['Motor','Mais velocidade final. Pequena perda de aceleração.','+1,8% velocidade / −0,9% aceleração'],['Rodas','Mais aderência para sustentar a linha nas curvas.','+3,5% aderência'],['Chassi','Mais leve para arrancar rápido. Menor velocidade final.','+3,5% aceleração / −0,7% velocidade']].map(function(p,i){var price=KT.Career.price(i);return '<article class="part"><div><span class="part-level">NÍVEL '+d.parts[i]+' / 3</span><h2>'+p[0]+'</h2><p>'+p[1]+'</p><small>'+p[2]+' por nível</small></div>'+button(price?'Melhorar · '+price:'Nível máximo','buy:'+i,'class="primary" '+(!price||d.bolts<price?'disabled':''))+'</article>';}).join('')+'<p class="setup-note">Ganhe Parafusos terminando corridas. Dificuldades maiores e pódios nas copas rendem mais.</p></section></div>';}
  function records(){var data=KT.Career.data,keys=Object.keys(data.records);return '<div class="page-heading"><div><span class="kicker">CONTRARRELÓGIO</span><h1>Cada centésimo conta.</h1></div><p>Recordes separados por pista, piloto e sentido. Seu melhor percurso fica salvo como fantasma.</p></div><div class="career-totals"><span><b>'+data.races+'</b> corridas</span><span><b>'+data.wins+'</b> vitórias</span><span><b>'+keys.length+'</b> fantasmas</span></div>'+(keys.length?'<div class="table-scroll"><table><thead><tr><th>Circuito</th><th>Piloto</th><th>Tempo · 3 voltas</th></tr></thead><tbody>'+keys.sort().map(function(k){var p=k.split(':');return '<tr><td>'+esc(KT.TRACKS[+p[0]]?KT.TRACKS[+p[0]].name:'Circuito')+(p[2]==='1'?' · espelhado':'')+'</td><td>'+esc(KT.DRIVERS[+p[1]]?KT.DRIVERS[+p[1]].nome:'Piloto')+'</td><td>'+KT.fmtTime(data.records[k].time)+'</td></tr>';}).join('')+'</tbody></table></div>':'<div class="empty-state"><span aria-hidden="true">◷</span><h2>A pista está esperando.</h2><p>Complete um contrarrelógio para salvar seu primeiro tempo e correr contra seu fantasma.</p>'+button('Começar contrarrelógio','time-trial','class="primary"')+'</div>');}
  function options(){var s=KT.Career.data.settings;return '<div class="page-heading"><div><span class="kicker">AJUSTE O GABINETE</span><h1>Pronto para a sua sessão.</h1></div></div><div class="options-list"><label>Volume <output id="volume-value">'+s.volume+'%</output><input type="range" id="volume" min="0" max="100" step="5" value="'+s.volume+'"></label><label class="toggle">Linhas de varredura CRT<input type="checkbox" id="crt" '+(s.crt?'checked':'')+'></label><label class="toggle">Partículas e efeitos de movimento<input type="checkbox" id="motion" '+(s.motion?'checked':'')+'></label><section><h2>Seu progresso fica neste navegador</h2><p>Copas, peças e fantasmas são salvos automaticamente. Exporte uma cópia para levar para outro navegador ou guardar um backup.</p><div class="button-row">'+button('Exportar progresso','export')+'<label class="file-button">Importar progresso<input type="file" id="import" accept="application/json,.json"></label></div><small>Importar substitui o progresso atual. Guarde uma exportação antes.</small></section><section><h2>Controle e teclado</h2><p>Controle padrão: A acelera/confirma, B freia/volta, X usa item, LB/RB derrapa, Start pausa. Analógico esquerdo ou direcional vira. Teclado: setas/WASD, Espaço, Z, Enter e Esc.</p><p id="pad-status">'+(KT.Controls&&KT.Controls.connected?'Controle conectado.':'Conecte um controle e pressione um botão para ativá-lo.')+'</p></section></div>';}
  function guide(){return '<div class="page-heading"><div><span class="kicker">DOMINE A CORRIDA</span><h1>Solte a Carga Trovão.</h1></div></div><div class="guide-layout"><section><h2>O básico</h2><dl><dt>Setas / WASD</dt><dd>Acelerar, frear, virar e dar ré.</dd><dt>Espaço / Shift</dt><dd>Segure durante a curva. Solte para converter carga em impulso.</dd><dt>Z / Ctrl</dt><dd>Usar o item equipado.</dd><dt>Esc / P</dt><dd>Pausar; Enter continua. Esc de novo volta ao menu.</dd><dt>C</dt><dd>Modo foto. Setas giram a câmera e mudam a altura; Enter salva PNG.</dd><dt>M / F</dt><dd>Silenciar / tela cheia.</dd></dl><h2>Largada relâmpago</h2><p>Acelere no último instante, entre o 1 e o VALENDO, para ganhar impulso.</p><h2>Três níveis de carga</h2><p>0,85 s: amarelo, 0,6 s de impulso. 1,75 s: magma, 1,05 s. 2,7 s: relâmpago, 1,55 s. As marcas na barra também indicam o nível.</p></section><section><h2>Seis maneiras de virar o jogo</h2>'+[['Turbina de Magma','Impulso imediato, melhor nas retas.'],['Esfera de Plasma','Persegue um adversário à frente.'],['Poça de Piche','Deixa uma armadilha atrás do kart.'],['Bolha de Força','Absorve um golpe; guarde para a ameaça chegar.'],['Mola Saltadora','Salta por 1,5 s, passando por perigos sem ser atingido.'],['Ímã de Reboque','Aproveita um kart até 260 unidades à frente para ganhar impulso.']].map(function(a){return '<h3>'+a[0]+'</h3><p>'+a[1]+'</p>';}).join('')+'</section></div>';}
  function results(){var r=lastRace,o=r.result||{reward:0},champ=o.championship;return '<div class="result-page"><span class="kicker">'+KT.TRACKS[r.trackId].name+'</span><h1>'+(r.mode==='tt'?(r.newRecord?'NOVO RECORDE!':'VOLTA AO RELÓGIO'):r.player.pos===1?'VITÓRIA!':'BANDEIRADA FINAL')+'</h1><div class="result-reward"><b>+'+o.reward+'</b> Parafusos'+(r.player.finished?' · '+KT.fmtTime(r.player.finishTime):' · Não terminou')+'</div>'+(o.unlock&&o.unlock.length?'<p class="unlock-message">LIBERADO: '+o.unlock.map(esc).join(' · ')+'</p>':'')+'<div class="result-columns"><section><h2>Resultado da corrida</h2><table><thead><tr><th>Pos.</th><th>Piloto</th><th>Tempo</th></tr></thead><tbody>'+r.karts.slice().sort(function(a,b){return a.pos-b.pos;}).map(function(k){return '<tr '+(k.isPlayer?'class="player-row"':'')+'><td>'+k.pos+'º</td><td>'+k.driver.nome+'</td><td>'+(k.finished?KT.fmtTime(k.finishTime):'DNF')+'</td></tr>';}).join('')+'</tbody></table><p>Melhor volta: '+KT.fmtTime(r.player.bestLap)+'</p></section>'+(champ?'<section><h2>'+KT.CUPS[champ.cup].name+' · '+champ.stage+'/10</h2><table><thead><tr><th>Piloto</th><th>Pontos</th></tr></thead><tbody>'+champ.table.map(function(x){return '<tr '+(x.driver===r.player.di?'class="player-row"':'')+'><td>'+KT.DRIVERS[x.driver].nome+'</td><td>'+x.points+'</td></tr>';}).join('')+'</tbody></table>'+(champ.done?'<p>Copa concluída! Sua posição: <b>'+champ.place+'º</b>.</p>':'<p>Progresso salvo. Você pode continuar agora ou voltar depois.</p>')+'</section>':'<section class="result-tip"><h2>'+(r.mode==='tt'?'Seu próximo adversário é você.':'Mais uma corrida?')+'</h2><p>'+(r.mode==='tt'?'O melhor percurso é salvo automaticamente. Na próxima tentativa, o fantasma mostra onde ganhar tempo.':'Acerte a linha, guarde seu escudo e libere a carga na saída da curva.')+'</p></section>')+'</div><div class="button-row">'+button(champ&&!champ.done?'PRÓXIMA ETAPA':'CORRER DE NOVO',champ&&!champ.done?'resume-cup':'retry','class="primary"')+button('Voltar ao menu','menu')+'</div></div>';}
  function render(){if(!root)return;root.innerHTML=header()+'<main class="menu-body">'+({free:free,online:online,cups:cups,garage:garage,records:records,options:options,guide:guide,results:results}[view]||free)()+'</main><footer class="menu-foot"><span>Teclado · Controle · Offline</span><span>'+ (KT.Career.storageOK?'Progresso salvo neste navegador':'Save indisponível: exporte seu progresso')+'</span></footer><div class="menu-notice" role="status" aria-live="polite"></div>';root.querySelectorAll('[data-face]').forEach(function(c){var d=KT.DRIVERS[+c.dataset.face];c.getContext('2d').drawImage(KT.Sprites.buildFace(d.cor,d.capacete,d.pele),0,0);});drawMap();drawGarage();if(view==='results'&&lastRace.mode==='online'){var next=root.querySelector('.result-page .primary');next.dataset.action='online-lobby';next.textContent=KT.Net.host?'VOLTAR À SALA':'AGUARDE O ANFITRIÃO';next.disabled=!KT.Net.host;}}
  function drawMap(){var c=root&&root.querySelector('#track-map');if(!c)return;var x=c.getContext('2d'),t=KT.TRACKS[choice.track],theme=KT.THEMES[t.theme],pts=[];
    for(var i=0;i<200;i++){var th=i/200*KT.TAU,w=t.waves,r=t.radius+w[0]*Math.sin(w[1]*th+w[2])+w[3]*Math.sin(w[4]*th+w[5])+w[6]*Math.cos(w[7]*th+w[8]);pts.push([Math.cos(th)*r*t.sx*(choice.mirror?-1:1),Math.sin(th)*r*t.sy]);}
    var minx=Math.min.apply(null,pts.map(function(p){return p[0];})),maxx=Math.max.apply(null,pts.map(function(p){return p[0];})),miny=Math.min.apply(null,pts.map(function(p){return p[1];})),maxy=Math.max.apply(null,pts.map(function(p){return p[1];})),scale=Math.min(390/(maxx-minx),220/(maxy-miny));
    x.fillStyle='#101927';x.fillRect(0,0,460,300);x.fillStyle='#243344';for(i=20;i<460;i+=24)for(var j=20;j<300;j+=24)x.fillRect(i,j,1,1);
    function path(){x.beginPath();pts.forEach(function(p,i){var px=230+(p[0]-(minx+maxx)/2)*scale,py=147+(p[1]-(miny+maxy)/2)*scale;if(!i)x.moveTo(px,py);else x.lineTo(px,py);});x.closePath();}
    path();x.lineJoin='round';x.lineWidth=17;x.strokeStyle='#2a3b4c';x.stroke();x.lineWidth=10;x.strokeStyle=theme.accent;x.stroke();x.lineWidth=5;x.strokeStyle='#13222e';x.stroke();var p=pts[0],sx=230+(p[0]-(minx+maxx)/2)*scale,sy=147+(p[1]-(miny+maxy)/2)*scale;x.fillStyle='#ffffff';x.fillRect(sx-5,sy-5,10,10);x.font='12px Consolas, monospace';x.fillText('LARGADA',sx>355?sx-68:sx+13,sy+5);
  }
  function drawGarage(){var c=root&&root.querySelector('#garage-preview');if(!c)return;var x=c.getContext('2d'),d=KT.DRIVERS[choice.driver],color=KT.Career.paints[KT.Career.data.paint]||d.cor,sprites=KT.Sprites.buildKart(color,d.capacete,d.pele);x.imageSmoothingEnabled=false;x.fillStyle='#111c2a';x.fillRect(0,0,220,140);x.fillStyle='#293d4c';x.fillRect(35,112,150,4);x.drawImage(KT.Sprites.kartFrame(sprites,.55),35,20,150,100);}
  function notice(msg){var n=root&&root.querySelector('.menu-notice');if(n){n.textContent=msg;n.classList.add('visible');}}
  function start(){KT.Game.start({jogador:choice.driver,pista:choice.track,nivel:choice.level,voltas:choice.mode==='tt'?3:choice.laps,modo:choice.mode,espelho:choice.mirror});}
  function download(name,text,type){var blob=new Blob([text],{type:type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function action(code){var pair=code.split(':'),a=pair[0],v=pair[1];KT.Audio.resume();KT.Audio.play('select');
    if(a==='tab'){if(v!=='online'&&KT.Net.connected)KT.Net.leave();view=v;render();}
    else if(a==='create-online'){KT.Net.create(nickname,choice.driver,{pista:choice.track,nivel:choice.level,voltas:choice.laps,espelho:choice.mirror});}
    else if(a==='join-online'){KT.Net.join(roomInput,nickname,choice.driver);}
    else if(a==='leave-online'){KT.Net.leave();view='online';render();}
    else if(a==='start-online'){KT.Net.start();}
    else if(a==='online-lobby'){view='online';KT.Net.backLobby();}
    else if(a==='copy-invite'){var invite=KT.Net.invite();if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(invite).then(function(){notice('Convite copiado. Envie para seus amigos!');}).catch(function(){root.querySelector('#invite-link').select();notice('Selecione e copie o link do convite.');});else {root.querySelector('#invite-link').select();notice('Selecione e copie o link do convite.');}}
    else if(a==='track'){choice.track=(choice.track+(+v)+30)%30;render();}
    else if(a==='driver'){choice.driver=+v;render();}
    else if(a==='cup'){choice.cup=+v;render();}
    else if(a==='start')start();
    else if(a==='begin-cup'){if(KT.Career.data.activeCup){notice('Você já tem uma copa em andamento. Continue-a ou encerre-a antes de iniciar outra.');var box=root.querySelector('.resume-cup');if(box&&!box.querySelector('[data-action="abandon-cup"]'))box.appendChild(Object.assign(document.createElement('button'),{type:'button',textContent:'Encerrar copa atual',onclick:function(){action('abandon-cup');}}));return;}if(KT.Career.beginCup(choice.cup,choice.level,choice.driver))KT.Game.start(KT.Career.cupConfig());}
    else if(a==='abandon-cup'){KT.Career.data.activeCup=null;KT.Career.save();render();notice('Copa encerrada. Seus Parafusos e desbloqueios foram mantidos.');}
    else if(a==='resume-cup'){var cfg=KT.Career.cupConfig();if(cfg)KT.Game.start(cfg);}
    else if(a==='buy'){if(KT.Career.buy(+v)){render();notice('Peça instalada!');}}
    else if(a==='paint'){KT.Career.paint(+v);render();}
    else if(a==='time-trial'){choice.mode='tt';choice.laps=3;view='free';render();}
    else if(a==='export'){download('kart-trovao-progresso.json',KT.Career.exportSave(),'application/json');notice('Cópia de progresso exportada.');}
    else if(a==='menu'){view='free';KT.Game.menu();}
    else if(a==='retry'){if(lastRace.mode==='cup'){view='cups';KT.Game.menu();}else KT.Game.start({jogador:lastRace.player.di,pista:lastRace.trackId,nivel:lastRace.level,voltas:lastRace.totalLaps,modo:lastRace.mode,espelho:lastRace.mirror});}
  }
  function applySettings(){var s=KT.Career.data.settings;document.getElementById('scanlines').style.display=s.crt?'':'none';document.documentElement.classList.toggle('reduced-motion',!s.motion);KT.Audio.setVolume(s.volume/100);}
  KT.UI={
    init:function(){if(root)return;var parent=document.getElementById('screen-wrap');if(!parent||!parent.appendChild)return;root=document.createElement('section');root.id='race-menu';root.hidden=true;root.setAttribute('aria-label','Menu do Kart Trovão');parent.appendChild(root);
      root.addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(b&&!b.disabled)action(b.dataset.action);});
      root.addEventListener('input',function(e){if(e.target.id==='online-name')nickname=e.target.value;if(e.target.id==='room-input')roomInput=e.target.value;});
      root.addEventListener('change',function(e){if(e.target.id==='online-driver')choice.driver=+e.target.value;});
      root.addEventListener('change',function(e){var t=e.target,id=t.id;if(id==='track')choice.track=+t.value;if(id==='level')choice.level=+t.value;if(id==='mode'){choice.mode=t.value;if(choice.mode==='tt')choice.laps=3;}if(id==='laps')choice.laps=+t.value;if(id==='mirror')choice.mirror=t.value==='1';if(id==='crt'||id==='motion'){KT.Career.data.settings[id]=t.checked;KT.Career.save();applySettings();return;}if(id==='import'&&t.files[0]){if(t.files[0].size>6000000){notice('Arquivo muito grande. Escolha um save exportado pelo jogo.');return;}t.files[0].text().then(function(text){KT.Career.importSave(text);if(!KT.Career.unlockedDriver(choice.driver))choice.driver=1;if(choice.level===3&&!KT.Career.legend())choice.level=1;applySettings();render();notice('Progresso importado.');}).catch(function(){notice('Não foi possível ler esse save. O progresso anterior foi mantido.');});return;}if(id!=='volume')render();});
      root.addEventListener('input',function(e){if(e.target.id==='volume'){var n=+e.target.value;KT.Career.data.settings.volume=n;KT.Career.save();KT.Audio.setVolume(n/100);root.querySelector('#volume-value').textContent=n+'%';}});
      root.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();if(view==='results'){view='free';KT.Game.menu();}else {view='free';render();}}});
      if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)KT.Career.data.settings.motion=false;
      applySettings();
      if(typeof location!=='undefined'&&/^#sala=/i.test(location.hash)){roomInput=location.hash.replace(/^#sala=/i,'');view='online';setTimeout(function(){KT.Game.menu();},100);}
    },
    show:function(){if(!root)return;if(view==='results')view='free';root.hidden=false;render();var b=root.querySelector('[aria-current="page"]');if(b)b.focus();},
    hide:function(){if(root){if(root.contains(document.activeElement))document.activeElement.blur();root.hidden=true;}},
    onlineChanged:function(){if(!root)return;if(view==='online'||(KT.Net.connected&&KT.Game.state==='select')){view='online';render();}},
    results:function(r){lastRace=r;view='results';if(root){root.hidden=false;render();var b=root.querySelector('.result-page .primary');if(b)b.focus();}},
    update:function(I){if(!root||root.hidden)return;var items=Array.from(root.querySelectorAll('button:not(:disabled),select:not(:disabled),input:not(:disabled)')).filter(function(e){return e.getClientRects().length;});var current=items.indexOf(document.activeElement);if(I.hit('down')||I.hit('right'))items[(current+1)%items.length]?.focus();if(I.hit('up')||I.hit('left'))items[(current-1+items.length)%items.length]?.focus();if(I.hit('start')){var target=document.activeElement;if(target&&target.tagName==='BUTTON')target.click();}if(I.hit('pause')){view='free';KT.Game.menu();}},
    capture:function(){var a=document.createElement('a');a.download='kart-trovao-'+KT.race.trackId+'.png';a.href=KT.Game.photoFrame();a.click();},
    notice:notice,applySettings:applySettings
  };
})();
